/*
 * Copyright (c) 2025. Bruno NDUWARUGIRA
 */

export enum Sex {
    MALE = "MALE",
    FEMALE = "FEMALE"
}

export enum Role {
    ADMIN = 'ADMIN',
    USER = 'USER',
    ADMIN_SUDO = 'ADMIN_SUDO',
    DEVELOPER = 'DEVELOPER', SECURITY_MANAGER = 'SECURITY_MANAGER',
    MANAGER_USERS = 'MANAGER_USERS', MANAGER_TRANSACTIONS = 'MANAGER_TRANSACTIONS',
    SERVICE_CLIENT = 'SERVICE_CLIENT',
    BUSINESS_NEEDS_ANALYST = 'BUSINESS_NEEDS_ANALYST',
    BUSINESS_ANALYST = 'BUSINESS_ANALYST',
    BUSINESS_DEVELOPER = 'BUSINESS_DEVELOPER',
    BUSINESS_MANAGER = 'BUSINESS_MANAGER',
    BUSINESS_OWNER = 'BUSINESS_OWNER',
    BUSINESS_PARTNER = 'BUSINESS_PARTNER',
    BUSINESS_PRODUCT_MANAGER = 'BUSINESS_PRODUCT_MANAGER',
    BUSINESS_PRODUCT_OWNER = 'BUSINESS_PRODUCT_OWNER',
    BUSINESS_TEAM_LEADER = 'BUSINESS_TEAM_LEADER',
    BUSINESS_USER = 'BUSINESS_USER',
    USER_STANDARD = 'USER_STANDARD',
    USER_PARTNER = 'USER_PARTNER'
}
